---
title: "R Notebook"
output:
<<<<<<< Updated upstream
  html_document: default
  html_notebook:
    fig_caption: yes
    tab_caption: yes
=======
  html_document: 
    highlight: zenburn
    theme: cerulean
  html_notebook: default
>>>>>>> Stashed changes
---

Perfom benchmarkinng tests on `sprawl::comp_zonal`

<<<<<<< Updated upstream
```{r, echo=FALSE, message=FALSE, warning=FALSE}

  library(sprawl)
  library(microbenchmark)
  library(profvis)
  library(raster)
  library(ggplot2)
  in_polys <- readshape(system.file("extdata","lc_polys.shp", package = "sprawl"), stringsAsFactors = T)
  in_rast  <- raster::stack(system.file("extdata", "sprawl_EVItest.tif", package = "sprawl"))
  mb = microbenchmark(
    raster_extract = {raster::extract(in_rast[[1:46]], as(in_polys, "Spatial"), FUN = mean, sp = T )}, 
    # b = {outsmall <- comp_zonal(in_rast, in_polys, verbose = FALSE, 
    #                        mode = "std", selbands = c(1,20), maxchunk = 5E4)},
    czonal_med = {comp_zonal(in_rast, in_polys, verbose = FALSE,
                           mode = "std", selbands = c(1,46),   maxchunk = 10E4, full_data = F, addgeom = T)},
    czonal_big = {comp_zonal(in_rast, in_polys, verbose = FALSE, 
                           mode = "std",selbands = c(1,46),    maxchunk = 100E4, full_data = F, addgeom = T)},
    times = 1)
  mbsumm <- summary(mb)
  
  kable(mbsumm, caption = "Execution time")
  
  ggplot(mbsumm, aes(x = expr, y = mean)) + geom_boxplot() +
    coord_cartesian(ylim = c(0,120)) + ylab("Execution Time") + theme_bw()
=======
```{r, echo=TRUE, warning=FALSE}
  library(ggplot2)
  library(sprawl)
  library(compiler)
  fc = cmpfun(comp_zonal)
  # in_rastfile <- "/Documents/Source/git/sprawl/inst/extdata/tif_world.tif"
  in_rast  <- build_testraster(200,200,1)
  in_shape <- readshape("/Documents/Source/git/sprawl/inst/extdata/grid_world.shp")
  npolys   <- 50
  in_polys <- in_shape[sample(1:5151, npolys),]
  
  mb <- microbenchmark::microbenchmark(
    out_std = comp_zonal(in_rast, in_polys, verbose = F),
    out_comp = fc(in_rast, in_polys, verbose = F), 
    times = 50
  )
  boxplot(mb) + theme_bw()
>>>>>>> Stashed changes

```
